### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'background_color'

### ISSUE THREAD

**Issue by ahtchow** [lucasjinreal/alfred#17]
Traceback (most recent call last):
  File "core/pointpillars_detector.py", line 156, in <module>
    detector.predict_on_nucenes_local_file(sys.argv[1])
  File "core/pointpillars_detector.py", line 146, in predict_on_nucenes_local_file
    draw_pcs_open3d(geometries)
  File "/usr/local/lib/python3.8/dist-packages/alfred/vis/pointcloud/pointcloud_vis.py", line 76, in draw_pcs_open3d
    opt.background_color = np.asarray([0, 0, 0])
AttributeError: 'NoneType' object has no attribute 'background_color'

when following: https://pythonawesome.com/a-deep-learning-utility-library-for-visualization-and-sensor-fusion-purpose/

**Comment by jinfagang** [comment]
@ahtchow As for open3d > 0.9.0, API seems changed a lot. I am not able to upgrade to latest one, I should but seems open3d not compatible on my system.

So please using open3d=0.9.0 for the moment.
