### ISSUE TITLE
Pip installation fails despite having colorama in dependencies

### ISSUE THREAD

**Issue by mantkiew** [lucasjinreal/alfred#23]
Got this error from a docker build of another system that depends on Alfred:
Ubuntu 20.04, Python 3.8.4, pip 22.0.2.
```
Collecting alfred-py
  Downloading alfred-py-2.10.0.tar.gz (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 51.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dc1ysaug/alfred-py_3fa144628b9e4c4795003ef8f4b41a70/setup.py", line 32, in <module>
          from alfred.alfred import __VERSION__
        File "/tmp/pip-install-dc1ysaug/alfred-py_3fa144628b9e4c4795003ef8f4b41a70/alfred/alfred.py", line 31, in <module>
          from colorama import Fore, Back, Style
      ModuleNotFoundError: No module named 'colorama'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jinfagang** [comment]
@mantkiew this is because of python3.9 above changed some dependency finding strategy. I added colorama to setup.py as dependencies now. You can try install from GitHub.
I will update pypi version soon.
